#pragma once
#define WINDOW_HEIGHT 600
#define WINDOW_WIDTH 1000
#define INVADER_WIDTH 30
#define INVADER_HEIGHT 20
#define SQUADRON_START_POS_WIDTH 20
#define SQUADRON_START_POS_HEIGHT 50
#define SQUADRON_COLUMNS 10
#define SQUADRON_ROWS 5
#define SQUADRON_SPACE_COLUMNS 10
#define SQUADRON_SPACE_ROWS 20
#define SQUADRON_MOVE_DOWN 20
#define SQUADRON_MOVE_X 30
#define SQUADRON_SHOOT_DELAY 1.2f
#define PLAYER_WIDTH 45
#define PLAYER_HEIGHT 30
#define PLAYER_SHOOT_DELAY 1
#define PLAYER_SPEED 3.2f
#define PLAYER_MOVE_DELAY 0.01f
#define SHIELD_WIDTH 60
#define SHIELD_HEIGHT 40
#define SHIELD_AMOUNT 6
#define SHIELD_POS_HEIGHT 450
#define SCORE_POS_WIDTH 0
#define SCORE_POS_HEIGHT 0 
#define FONT_SIZE 18
#define PROJECTILE_WIDTH 5
#define PROJECTILE_HEIGHT 10
#define SQUADRON_SWITCH_TIME 2.0f
#define PROJECTILE_SWITCH_TIME 0.02f
#define PROJECTILE_SPEED 4
#define INVADER_DEATH_SCORE 100
#define PLAYER_HEALTH_MINUS_SCORE 500
#define BUTTON_WIDTH 340
#define BUTTON_HEIGHT 60

//MENU
#define MENU_LOGO_HEIGHT 50
#define MENU_SPACING 50

//SAVE
#define SAVE_FILE "zapis.txt"

#define ERROR 404